name = "myproj"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Myproj"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3
## Silence noisy project-wide linters so only relevant issues show up
linter.unnecessarySimpa = false
linter.unusedSimpArgs = false
linter.style.longLine = false
linter.style.openClassical = false
linter.style.cdot = false
linter.unusedTactic = false
linter.unreachableTactic = false
linter.unusedVariables = false

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "Myproj"
